CREATE TABLE CURSO (
    cod char(4) NOT NULL,
    descripcion varchar(40) NOT NULL,
    tipo char(1) NOT NULL,
)

ALTER TABLE CURSO 
    ADD CONSTRAINT PK_CURSO
    PRIMARY KEY (cod)

CREATE TABLE ALUMNO (
    LU integer(5) NOT NULL, 
    nombre varchar(40) NOT NULL,
    provincia varchar(30) NOT NULL
)

ALTER TABLE ALUMNO
    ADD CONSTRAINT PK_ALUMNO
    PRIMARY KEY (LU)

CREATE TABLE INSCRIPTO (
    cod char(4) NOT NULL,
    LU integer(5) NOT NULL,
)

ALTER TABLE INSCRIPTO
    ADD CONSTRAINT PK_INSCRIPTO
    PRIMARY KEY (cod, LU)

ALTER TABLE INSCRIPTO
    ADD CONSTRAINT FK_INSCRIPTO_CURSO
    FOREIGN KEY (cod)
    REFERENCES CURSO(cod)

ALTER TABLE INSCRIPTO
    ADD CONSTRAINT FK_INSCRIPTO_ALUMNO
    FOREIGN KEY (LU)
    REFERENCES ALUMNO(LU)

-- acá está la magia del curso:
ALTER TABLE CURSO
    ADD CONSTRAINT FK_CURSO_REFERENTE_INSCRIPTO
    FOREIGN KEY (cod, LU)
    REFERENCES INSCRIPTO(cod, lU)

    -- consultar si está bien la referencia